version: '3.7'

services:
  server:
    image: backend
    ports:
      - 3000:3000
    working_dir: /backend
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./:/backend
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db


  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mongodb-data:
